/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "transfer.h"

void write_file(char* content){
	FILE *fp;
	fp = fopen("sample", "wb");
	fprintf(fp, content);
	fclose(fp);
}

void
transfer_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	file  transf_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TRANSFER, TRANSFER_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	FILE *fp;
	char filetotransf[] = "sample";

	write_file("Hello guys");
	fp = fopen(filetotransf, "rb");
	
	if(fp == NULL) {
		printf("File not found.\n");
		exit(1);
	}

	printf("Sending file %s.\n", filetotransf);

	strcpy(transf_1_arg.name, filetotransf);

	while(1) {
		transf_1_arg.nbytes = fread(transf_1_arg.data, 1, SIZE, fp);

		result_1 = transf_1(&transf_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		
		if(transf_1_arg.nbytes < SIZE) {
			printf("Completed file transfer.\n");
			break;
		}
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	transfer_1 (host);
exit (0);
}
